steps:
  # Install dependencies and run tests
  - name: 'python:3.11'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installing dependencies..."
        pip install -r requirements.txt
        
        echo "Running syntax checks..."
        python -m py_compile app/__init__.py
        python -m py_compile main.py
        python -m py_compile config.py
        
        echo "Running basic import tests..."
        python -c "from app import create_app; print('✅ App imports successfully')"
        
        echo "✅ All checks passed!"

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'app'
      - 'deploy' 
      - 'app.yaml'
      - '--quiet'
      - '--promote'
      - '--stop-previous-version'

  # Run database migrations
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running database migrations..."
        gcloud app exec -- python -c "
        from app import create_app, db
        from flask_migrate import upgrade
        app = create_app()
        with app.app_context():
            upgrade()
            print('✅ Database migrations completed')
        "

  # Warm up the application
  - name: 'gcr.io/cloud-builders/curl'
    args: 
      - '-f'
      - 'https://${PROJECT_ID}.appspot.com/health'

# Specify timeout for the entire build
timeout: '1200s'

# Use a more powerful machine for faster builds
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Set up build triggers
trigger:
  github:
    owner: 'your-github-username'  # Update with your GitHub username
    name: 'short_term_land_lord'   # Update with your repository name
    push:
      branch: '^main$'  # Trigger on pushes to main branch

# Environment variables for the build
substitutions:
  _DEPLOY_REGION: 'us-central1'