services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - FLASK_APP=app.py
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    command: >
      bash -c "sleep 5 &&
               if [ ! -d 'migrations' ] || [ ! -f 'migrations/env.py' ]; then
                 flask db init;
               fi &&
               flask db migrate -m 'Initial migration' || true &&
               python add_user_columns.py &&
               if [[ \$DATABASE_URL == *sqlite* ]]; then
                 python fix_sqlite_columns.py;
               fi &&
               python fix_database.py &&
               python fix_postgresql_enums.py &&
               python test_user_search.py &&
               python check_database.py &&
               python patch_user_model.py &&
               python model_fix.py &&
               python app_init_patch.py &&
               python test_model_fix.py &&
               flask run --host=0.0.0.0"

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "5434:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
