services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      # Mount the entire project directory
      - .:/app
      # Use named volumes to preserve important data
      - template_files:/app/app/templates/custom
      - migrations_data:/app/migrations
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db/flask_app
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flask_app
    ports:
      - "5434:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  template_files:
  migrations_data:
