name = "short-term-landlord"
compatibility_date = "2024-09-21"
main = "functions/_middleware.ts"

# Account ID from wrangler whoami
account_id = "04eac09ae835290383903273f68c79b0"

# D1 Database bindings
[[d1_databases]]
binding = "DB"
database_name = "short-term-landlord-db"
database_id = "fb1bde66-9837-4358-8c71-19be2a88cfee"

# KV namespace for caching and sessions
[[kv_namespaces]]
binding = "KV"
id = "48afc9fe53a3425b8757e9dc526c359e"

# R2 bucket for file storage (photos, videos, documents)
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "short-term-landlord-files"

# Cron triggers for calendar sync (every 2 hours)
[triggers]
crons = ["0 */2 * * *"]

# Build configuration
[build]
command = "npm run build"

# Environment variables (non-secret)
[vars]
ENVIRONMENT = "production"
FRONTEND_URL = "https://openbnb.me"

# Email provider configuration
EMAIL_PROVIDER = "ses"  # Options: ses, mailgun, sendgrid, or leave empty for dev mode
EMAIL_FROM = "no-reply@openbnb.me"

# Secret environment variables (set using: wrangler pages secret put <KEY> --project-name=short-term-landlord)
# These should NOT be committed to version control
#
# Required secrets:
# - JWT_SECRET: Secret key for JWT token signing (generate with: openssl rand -base64 32)
#     wrangler pages secret put JWT_SECRET --project-name=short-term-landlord
#
# Email provider secrets (choose one):
#
# For AWS SES (recommended):
# - SES_SMTP_HOST: SES SMTP endpoint (e.g., email-smtp.us-east-1.amazonaws.com)
#     wrangler pages secret put SES_SMTP_HOST --project-name=short-term-landlord
# - SES_SMTP_PORT: SMTP port (usually 587)
#     wrangler pages secret put SES_SMTP_PORT --project-name=short-term-landlord
# - SES_SMTP_USERNAME: SES SMTP username (IAM credentials)
#     wrangler pages secret put SES_SMTP_USERNAME --project-name=short-term-landlord
# - SES_SMTP_PASSWORD: SES SMTP password (IAM secret)
#     wrangler pages secret put SES_SMTP_PASSWORD --project-name=short-term-landlord
# - SES_REGION: AWS region (e.g., us-east-1)
#     wrangler pages secret put SES_REGION --project-name=short-term-landlord
#
# For Mailgun:
# - MAILGUN_API_KEY: Mailgun API key
#     wrangler pages secret put MAILGUN_API_KEY --project-name=short-term-landlord
# - MAILGUN_DOMAIN: Mailgun domain (e.g., mg.yourdomain.com)
#     wrangler pages secret put MAILGUN_DOMAIN --project-name=short-term-landlord
#
# For SendGrid:
# - SENDGRID_API_KEY: SendGrid API key
#     wrangler pages secret put SENDGRID_API_KEY --project-name=short-term-landlord
#
# To list all secrets: wrangler pages secret list --project-name=short-term-landlord
# To delete a secret: wrangler pages secret delete <KEY> --project-name=short-term-landlord

# Pages configuration for frontend
pages_build_output_dir = "dist"
