"""Initial migration

Revision ID: 1176f29a5d51
Revises: 652248a5d234
Create Date: 2025-03-30 08:46:21.062677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1176f29a5d51'
down_revision = '652248a5d234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=False),
    sa.Column('square_feet', sa.Integer(), nullable=True),
    sa.Column('bed_type', sa.String(length=50), nullable=True),
    sa.Column('has_tv', sa.Boolean(), nullable=True),
    sa.Column('tv_details', sa.String(length=100), nullable=True),
    sa.Column('has_shower', sa.Boolean(), nullable=True),
    sa.Column('has_tub', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurrence_pattern', sa.Enum('NONE', 'DAILY', 'WEEKLY', 'MONTHLY', 'CUSTOM', name='recurrencepattern'), nullable=True),
    sa.Column('recurrence_interval', sa.Integer(), nullable=True),
    sa.Column('recurrence_end_date', sa.DateTime(), nullable=True),
    sa.Column('linked_to_checkout', sa.Boolean(), nullable=True),
    sa.Column('calendar_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['property_calendar.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('external_name', sa.String(length=100), nullable=True),
    sa.Column('external_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_property',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'property_id')
    )
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ical_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('property_calendar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_error', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_calendar', schema=None) as batch_op:
        batch_op.drop_column('sync_error')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('ical_url')

    op.drop_table('task_property')
    op.drop_table('task_assignment')
    op.drop_table('task')
    op.drop_table('room')
    # ### end Alembic commands ###
