"""Add cleaner-specific fields to Property model

Revision ID: 1e7861017ca8
Revises: e5a7b2c8d9f0
Create Date: 2025-03-30 08:05:54.482641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7861017ca8'
down_revision = 'e5a7b2c8d9f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_beds', sa.Integer(), nullable=True, comment='Total number of beds in the property'))
        batch_op.add_column(sa.Column('bed_sizes', sa.String(length=255), nullable=True, comment='Description of bed sizes (e.g., "1 King, 2 Queen, 1 Twin")'))
        batch_op.add_column(sa.Column('number_of_tvs', sa.Integer(), nullable=True, comment='Number of TVs in the property'))
        batch_op.add_column(sa.Column('number_of_showers', sa.Integer(), nullable=True, comment='Number of showers'))
        batch_op.add_column(sa.Column('number_of_tubs', sa.Integer(), nullable=True, comment='Number of bathtubs'))
        batch_op.add_column(sa.Column('cleaning_supplies_location', sa.Text(), nullable=True, comment='Description of where cleaning supplies are stored'))
        batch_op.add_column(sa.Column('wifi_network', sa.String(length=100), nullable=True, comment='WiFi network name'))
        batch_op.add_column(sa.Column('wifi_password', sa.String(length=100), nullable=True, comment='WiFi password'))
        batch_op.add_column(sa.Column('special_instructions', sa.Text(), nullable=True, comment='Any special instructions for cleaners'))
        batch_op.add_column(sa.Column('entry_instructions', sa.Text(), nullable=True, comment='Instructions for entering the property (key codes, etc.)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('entry_instructions')
        batch_op.drop_column('special_instructions')
        batch_op.drop_column('wifi_password')
        batch_op.drop_column('wifi_network')
        batch_op.drop_column('cleaning_supplies_location')
        batch_op.drop_column('number_of_tubs')
        batch_op.drop_column('number_of_showers')
        batch_op.drop_column('number_of_tvs')
        batch_op.drop_column('bed_sizes')
        batch_op.drop_column('total_beds')

    # ### end Alembic commands ###
