"""Initial migration

Revision ID: 652248a5d234
Revises: 1e7861017ca8
Create Date: 2025-03-30 08:16:54.588252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652248a5d234'
down_revision = '1e7861017ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ical_url', sa.String(length=500), nullable=False),
    sa.Column('is_entire_property', sa.Boolean(), nullable=True),
    sa.Column('room_name', sa.String(length=100), nullable=True),
    sa.Column('service', sa.String(length=20), nullable=False),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_calendar')
    # ### end Alembic commands ###
