"""Add guest access fields to Property model

Revision ID: ae789f6b2ac8
Revises: cb0d5c79abef
Create Date: 2025-03-30 11:29:16.482826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae789f6b2ac8'
down_revision = 'cb0d5c79abef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_access_token', sa.String(length=64), nullable=True, comment='Unique token for guest access link'))
        batch_op.add_column(sa.Column('guest_rules', sa.Text(), nullable=True, comment='House rules for guests'))
        batch_op.add_column(sa.Column('guest_checkin_instructions', sa.Text(), nullable=True, comment='Check-in instructions for guests'))
        batch_op.add_column(sa.Column('guest_checkout_instructions', sa.Text(), nullable=True, comment='Check-out instructions for guests'))
        batch_op.add_column(sa.Column('guest_wifi_instructions', sa.Text(), nullable=True, comment='WiFi instructions for guests'))
        batch_op.add_column(sa.Column('local_attractions', sa.Text(), nullable=True, comment='Information about local attractions'))
        batch_op.add_column(sa.Column('emergency_contact', sa.String(length=255), nullable=True, comment='Emergency contact information'))
        batch_op.add_column(sa.Column('guest_access_enabled', sa.Boolean(), nullable=True, comment='Whether guest access is enabled'))
        batch_op.create_unique_constraint(None, ['guest_access_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('guest_access_enabled')
        batch_op.drop_column('emergency_contact')
        batch_op.drop_column('local_attractions')
        batch_op.drop_column('guest_wifi_instructions')
        batch_op.drop_column('guest_checkout_instructions')
        batch_op.drop_column('guest_checkin_instructions')
        batch_op.drop_column('guest_rules')
        batch_op.drop_column('guest_access_token')

    # ### end Alembic commands ###
