"""Add Room model and ical_url to Property

Revision ID: d0ddffee015b
Revises: c30ca987c580
Create Date: 2025-03-30 08:56:30.775842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ddffee015b'
down_revision = 'c30ca987c580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning_session', schema=None) as batch_op:
        batch_op.drop_index('ix_cleaning_session_cleaner_id')
        batch_op.drop_index('ix_cleaning_session_property_id')
        batch_op.drop_index('ix_cleaning_session_task_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning_session', schema=None) as batch_op:
        batch_op.create_index('ix_cleaning_session_task_id', ['task_id'], unique=False)
        batch_op.create_index('ix_cleaning_session_property_id', ['property_id'], unique=False)
        batch_op.create_index('ix_cleaning_session_cleaner_id', ['cleaner_id'], unique=False)

    # ### end Alembic commands ###
