"""Add external_email to TaskAssignment

Revision ID: dd6012cf26dd
Revises: dcf4f3977087
Create Date: 2025-03-30 13:54:11.599998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6012cf26dd'
down_revision = 'dcf4f3977087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_assignment', schema=None) as batch_op:
        batch_op.drop_column('external_email')

    # ### end Alembic commands ###
