"""Initial migration

Revision ID: fd582bab23f5
Revises: 7f3c9368d101
Create Date: 2025-03-30 10:04:06.651794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd582bab23f5'
down_revision = '7f3c9368d101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assign_to_next_cleaner', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('assign_to_next_cleaner')

    # ### end Alembic commands ###
